### ISSUE TITLE
README.md build instructions seem to not work

### ISSUE THREAD

**Issue by samhansen** [openweave/openweave-esp32-demo#11]
I'm having a hard time building the demo app.  I'm installing a fresh version of the esp-idf and xtensa toolchain.

The espressif sdk/toolchain was configured as:
```
git clone --recursive https://github.com/espressif/esp-idf.git
cd esp-idf
./install.sh
git checkout release/v3.0
```

The install script installed the toolchain to `~/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin`, which contains the `xtensa-esp32-elf-gcc` toolchain.

The demo app was configured as:
```
git clone https://github.com/openweave/openweave-esp32-demo.git
cd openweave-esp32-demo
git submodule init
git submodule update
. setup.sh
make defconfig
```

Upon issuing `make`, the following error is returned:
```
WARNING: esp-idf git submodule components/esptool_py/esptool may be out of date. Run 'git submodule update' in IDF_PATH dir to update.
WARNING: Failed to find Xtensa toolchain, may need to alter PATH or set one in the configuration menu
WARNING: esp-idf git submodule components/esptool_py/esptool may be out of date. Run 'git submodule update' in IDF_PATH dir to update.
WARNING: Failed to find Xtensa toolchain, may need to alter PATH or set one in the configuration menu
WARNING: esp-idf git submodule components/esptool_py/esptool may be out of date. Run 'git submodule update' in IDF_PATH dir to update.
/home/sam/Vol/esp-idf/make/project.mk:502: warning: undefined variable 'which git'
WARNING: Missing submodule components/esp32/lib...
Attempting 'git submodule update --init components/esp32/lib' in esp-idf root directory...
Submodule 'components/esp32/lib' (https://github.com/espressif/esp32-wifi-lib.git) registered for path 'components/esp32/lib'
Cloning into '/home/sam/Vol/esp-idf/components/esp32/lib'...
Submodule path 'components/esp32/lib': checked out 'ac3108200a0ac7bd58b060fa4d5e389827290d63'
CC build/bootloader/bootloader_support/src/efuse.o
CC build/bootloader/bootloader_support/src/bootloader_flash.o
CC build/bootloader/bootloader_support/src/secure_boot_signatures.o
/home/sam/Vol/esp-idf/components/bootloader_support/src/secure_boot_signatures.c:22:10: fatal error: uECC.h: No such file or directory
 #include "uECC.h"
          ^~~~~~~~
compilation terminated.
make[2]: *** [/home/sam/Vol/esp-idf/make/component_wrapper.mk:274: src/secure_boot_signatures.o] Error 1
make[1]: *** [/home/sam/Vol/esp-idf/make/project.mk:450: component-bootloader_support-build] Error 2
make: *** [/home/sam/Vol/esp-idf/components/bootloader/Makefile.projbuild:40: /home/sam/Vol/openweave/openweave-esp32-demo/build/bootloader/bootloader.bin] Error 2
```

Note that updating the esp-idf components doesn't resolve the header compilation error.

**Comment by samhansen** [comment]
Oh, also, the contents of my `setup.sh` is as follows:

```
#!/bin/bash
IDF_PATH=/home/sam/Vol/esp-idf
ESP32_TOOLS_BIN=/home/sam/.espressif/tools/xtensa-esp32-elf/esp-2019r2-8.2.0/xtensa-esp32-elf/bin
export PATH=${ESP32_TOOLS_BIN}:${PATH}
export IDF_PATH
```

**Comment by jaylogue** [comment]
Sorry for the confusion here.  It seems there are a few problems.  

It looks like the Getting Started pages for ESP-IDF 3.0 version are dead.  Here the correct set of commands to set up the SDK tree for this version:

```
$ git clone https://github.com/espressif/esp-idf.git
$ cd esp-idf
$ git checkout release/v3.0
$ git submodule update --init
```

Additionally, one must use the 1.22.0-80-g6c4433a-5.2.0 version of the xtensa esp32 tool chain when building with ESP-IDF v3.0.  This can be downloaded here: [https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz](https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz)

(EDIT: corrected cut-and-paste error in above instructions).

**Comment by samhansen** [comment]
I just replicated the environment as set up by `.travis/{build,prepare}.sh`.  There appear to be two key differences:

1. The toolchain is pinned to [xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0](https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz).
2. The eps-idf repo is checked out at the commit tagged at v3.0.4.

Having made those two adjustments, the build succeeds.  I suspect the README.md file simply needs updating.  I might send a follow-up pullreq.

**Comment by samhansen** [comment]
Whoops, looks like our updates crossed in flight :)

I can see you've self-assigned this issue.  Let me know if I can do anything further to help on this issue.  If you plan on updating the README doc, I suspect this issue can be closed.
