### ISSUE TITLE
Unable to build demo application

### ISSUE THREAD

**Issue by Kottapalli-Naveen** [openweave/openweave-esp32-demo#4]
Hello,

Am seeing the below error while trying to build the demo application based on the instructions given in main page.  Below is the error.  Can anyone tell how can this be fixed?

{noformat:}
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_api.o):(.text.esp_wifi_scan_get_ap_records+0x8): undefined reference to `esp_mesh_is_scan_allowed'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_api.o): In function `esp_wifi_scan_get_ap_records':
(.text.esp_wifi_scan_get_ap_records+0x10c): undefined reference to `esp_mesh_is_scan_allowed'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `pll_correct_dcap':
(.iram1+0x1c4): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `pll_correct_dcap':
(.iram1+0x1c8): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `pll_correct_dcap':
(.iram1+0x1cf): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `phy_unforce_wifi_chan':
(.iram1+0x234): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `phy_dis_hw_set_freq':
(.iram1+0x27b): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `phy_force_wifi_chan':
(.iram1+0x310): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `phy_force_wifi_chan':
(.iram1+0x31f): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `ram_chip_i2c_writeReg':
(.iram1+0x3c4): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `ram_chip_i2c_writeReg':
(.iram1+0x3df): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `ram_chip_i2c_readReg':
(.iram1+0x4c8): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `ram_chip_i2c_readReg':
(.iram1+0x4eb): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `phy_en_hw_set_freq':
(.iram1+0x576): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `wifi_track_pll_cap':
(.iram1+0x59b): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `wifi_track_pll_cap':
(.iram1+0x60a): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o):(.text.ram_pbus_force_mode+0x18): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o):(.text.ram_pbus_force_mode+0x27): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `ram_pbus_force_mode':
(.text.ram_pbus_force_mode+0x93): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o):(.text.chip_v7_set_chan+0xc): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o):(.text.chip_v7_set_chan+0x10): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `chip_v7_set_chan':
(.text.chip_v7_set_chan+0x5d): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `chip_v7_set_chan':
(.text.chip_v7_set_chan+0x91): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o):(.text.chip_v7_set_chan_offset+0xf): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_ana.o): In function `chip_v7_set_chan_offset':
(.text.chip_v7_set_chan_offset+0xb8): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7.o): In function `ram_bb_bss_cbw40_dig':
(.text.ram_bb_bss_cbw40_dig+0xb): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7.o): In function `ram_bb_bss_bw_40_en':
(.text.ram_bb_bss_bw_40_en+0xb): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7.o): In function `bb_init':
(.text.bb_init+0x396): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7.o): In function `bb_init':
(.text.bb_init+0x3a9): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7.o): In function `bb_init':
(.text.bb_init+0x3b9): undefined reference to `esp_dport_access_reg_read'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7.o):(.text.bb_init+0x3cc): more undefined references to `esp_dport_access_reg_read' follow
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_cal.o): In function `ram_set_txcap_reg':
(.iram1+0xbe7): undefined reference to `phy_enter_critical'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libphy.a(phy_chip_v7_cal.o): In function `tx_pwctrl_background':
(.iram1+0xcfd): undefined reference to `phy_exit_critical'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(ld_acl.o): In function `ld_sco_end':
ld_acl.c:(.iram1.text+0x404): undefined reference to `ld_acl_rx'
ld_acl.c:(.iram1.text+0x408): undefined reference to `ld_acl_tx'
ld_acl.c:(.iram1.text+0x40c): undefined reference to `ld_acl_rx_sync2'
ld_acl.c:(.iram1.text+0x410): undefined reference to `ld_acl_rx_sync'
ld_acl.c:(.iram1.text+0x414): undefined reference to `ld_acl_rx_no_sync'
ld_acl.c:(.iram1.text+0x418): undefined reference to `ld_sco_modify'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(ld_acl.o): In function `ld_sco_frm_isr_wrapper':
ld_acl.c:(.iram1.text+0x4ef): undefined reference to `ld_acl_rx'
ld_acl.c:(.iram1.text+0x4fa): undefined reference to `ld_acl_tx'
ld_acl.c:(.iram1.text+0x53f): undefined reference to `ld_acl_rx_sync2'
ld_acl.c:(.iram1.text+0x54a): undefined reference to `ld_acl_rx_sync'
ld_acl.c:(.iram1.text+0x55c): undefined reference to `ld_acl_rx_no_sync'
ld_acl.c:(.iram1.text+0x5da): undefined reference to `ld_sco_modify'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(ld_fm.o):(.iram1.text+0x20): undefined reference to `ld_acl_sniff_frm_cbk'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(ld_fm.o): In function `r_ld_fm_sket_isr':
ld_fm.c:(.iram1.text+0x164): undefined reference to `ld_sco_frm_cbk'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(ld_fm.o): In function `r_ld_fm_frame_isr':
ld_fm.c:(.iram1.text+0x2ee): undefined reference to `ld_acl_sniff_frm_cbk'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(rwip.o):(.text+0x0): undefined reference to `rwip_env'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(rwip.o): In function `r_rwip_wakeup':
rwip.c:(.iram1.text+0x5c): undefined reference to `rwip_env'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_hostap.o):(.text.ieee80211_hostap_send_beacon_process+0x0): undefined reference to `esp_mesh_quick_funcs'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_hostap.o):(.text.hostap_input+0x54): undefined reference to `is_esp_mesh_assoc'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_hostap.o): In function `hostap_input':
(.text.hostap_input+0xd72): undefined reference to `is_esp_mesh_assoc'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_ie_crypto_key_set_progress+0xc): undefined reference to `mesh_set_ie_crypto_config'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_ie_crypto_key_set_progress':
(.text.wifi_mesh_ie_crypto_key_set_progress+0x9f): undefined reference to `mesh_set_ie_crypto_config'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_parent_candidate_set_progress+0x10): undefined reference to `mesh_set_parent_candidate'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_parent_candidate_set_progress':
(.text.wifi_mesh_parent_candidate_set_progress+0xb4): undefined reference to `mesh_set_parent_candidate'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_parent_candidate_clear_progress+0x0): undefined reference to `mesh_clear_parent_candidate'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_parent_candidate_clear_progress':
(.text.wifi_mesh_parent_candidate_clear_progress+0x7): undefined reference to `mesh_clear_parent_candidate'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_ie_set_progress+0x8): undefined reference to `ieee80211_vnd_mesh_quick_set'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_ie_set_progress':
(.text.wifi_mesh_ie_set_progress+0x48): undefined reference to `ieee80211_vnd_mesh_quick_set'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_ie_get_progress+0x8): undefined reference to `ieee80211_vnd_mesh_quick_get'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_ie_get_progress':
(.text.wifi_mesh_ie_get_progress+0x48): undefined reference to `ieee80211_vnd_mesh_quick_get'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_roots_ie_set_progress+0x8): undefined reference to `ieee80211_vnd_mesh_roots_set'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_roots_ie_set_progress':
(.text.wifi_mesh_roots_ie_set_progress+0x5a): undefined reference to `ieee80211_vnd_mesh_roots_set'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_roots_ie_get_progress+0x8): undefined reference to `ieee80211_vnd_mesh_roots_get'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_roots_ie_get_progress':
(.text.wifi_mesh_roots_ie_get_progress+0x5a): undefined reference to `ieee80211_vnd_mesh_roots_get'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_ie_crypto_funcs_set_progress':
(.text.wifi_mesh_ie_crypto_funcs_set_progress+0x57): undefined reference to `mesh_set_ie_crypto_config'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_parent_monitor_set_progress+0x8): undefined reference to `mesh_set_parent_monitor_config'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_parent_monitor_set_progress':
(.text.wifi_mesh_parent_monitor_set_progress+0x44): undefined reference to `mesh_set_parent_monitor_config'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_parent_monitor_get_progress+0x8): undefined reference to `mesh_get_parent_monitor_config'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_parent_monitor_get_progress':
(.text.wifi_mesh_parent_monitor_get_progress+0x44): undefined reference to `mesh_get_parent_monitor_config'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_parent_candidate_get_progress+0x8): undefined reference to `mesh_get_parent_candidate'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_parent_candidate_get_progress':
(.text.wifi_mesh_parent_candidate_get_progress+0x44): undefined reference to `mesh_get_parent_candidate'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_rssi_threshold_set_progress+0x8): undefined reference to `mesh_set_rssi_threshold'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_rssi_threshold_set_progress':
(.text.wifi_mesh_rssi_threshold_set_progress+0x44): undefined reference to `mesh_set_rssi_threshold'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o):(.text.wifi_mesh_rssi_threshold_get_progress+0x8): undefined reference to `mesh_get_rssi_threshold'
/home/sriram/work/oweave/esp/esp-idf/components/esp32/lib/libnet80211.a(ieee80211_ioctl.o): In function `wifi_mesh_rssi_threshold_get_progress':
(.text.wifi_mesh_rssi_threshold_get_progress+0x44): undefined reference to `mesh_get_rssi_threshold'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(dbg_task.o): In function `hci_vendor_ble_long_adv_cmd_handler':
dbg_task.c:(.text+0x13c): undefined reference to `dbg_default_state'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(lc_task.o): In function `lc_dhkey_computation_start':
lc_task.c:(.text+0x5a0): undefined reference to `lm_get_auth_method'
lc_task.c:(.text+0x5a4): undefined reference to `lc_set_encap_pdu_data_p256'
lc_task.c:(.text+0x5a8): undefined reference to `lc_set_encap_pdu_data_p192'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(lc_task.o): In function `lmp_encaps_payl_handler':
lc_task.c:(.text+0x723): undefined reference to `lm_get_auth_method'
lc_task.c:(.text+0x7d6): undefined reference to `lc_set_encap_pdu_data_p256'
lc_task.c:(.text+0x7e6): undefined reference to `lc_set_encap_pdu_data_p192'
lc_task.c:(.text+0x7f6): undefined reference to `lc_set_encap_pdu_data_p256'
lc_task.c:(.text+0x806): undefined reference to `lc_set_encap_pdu_data_p192'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(bt_util_sp.o):(.text+0x4): undefined reference to `lm_n192_mod_mul'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(bt_util_sp.o):(.text+0x8): undefined reference to `lm_n192_mod_add'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(bt_util_sp.o):(.text+0xc): undefined reference to `lm_n192_mod_sub'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(bt_util_sp.o): In function `r_lm_dhkey_calc_init':
bt_util_sp.c:(.text+0xf7): undefined reference to `lm_n192_mod_mul'
bt_util_sp.c:(.text+0x106): undefined reference to `lm_n192_mod_mul'
bt_util_sp.c:(.text+0x116): undefined reference to `lm_n192_mod_mul'
bt_util_sp.c:(.text+0x123): undefined reference to `lm_n192_mod_add'
bt_util_sp.c:(.text+0x132): undefined reference to `lm_n192_mod_add'
bt_util_sp.c:(.text+0x141): undefined reference to `lm_n192_mod_sub'
bt_util_sp.c:(.text+0x14f): undefined reference to `lm_n192_mod_add'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(ecc_p256.o):(.text+0x14): undefined reference to `ecc_point_multiplication_uint8_256'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(ecc_p256.o): In function `r_ecc_generate_key256_with_check':
ecc_p256.c:(.text+0x3fa): undefined reference to `ecc_point_multiplication_uint8_256'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(lc_sco.o):(.text+0x0): undefined reference to `lc_sco_env'
/home/sriram/work/oweave/esp/esp-idf/components/bt/lib/libbtdm_app.a(lc_sco.o): In function `r_lc_sco_reset':
lc_sco.c:(.text+0x5c): undefined reference to `lc_sco_data_path_config'
collect2: error: ld returned 1 exit status
/home/sriram/work/oweave/esp/esp-idf/make/project.mk:388: recipe for target '/home/sriram/work/oweave/esp/esp-idf/openweave-esp32-demo/build/openweave-esp32-demo.elf' failed
make: *** [/home/sriram/work/oweave/esp/esp-idf/openweave-esp32-demo/build/openweave-esp32-demo.elf] Error 1
{noformat:}

**Comment by jaylogue** [comment]
This looks to be a problem with a missing ESP-IDF library.  Which version of ESP-IDF are you using? 

The OpenWeave demo application currently builds against the 3.0.x version of ESP-IDF.  Later versions (3.1.x) will likely work, but may require some minor tweaks to resolve issues like the one you're seeing.

**Comment by Kottapalli-Naveen** [comment]
This is what I see in git status

{noformat:}
sriram@sriram-HP-Compaq-8200-Elite-CMT-PC:~/work/oweave/esp/esp-idf$ git status
On branch release/v3.0
Your branch is up-to-date with 'origin/release/v3.0'.
{noformat:}

**Comment by jaylogue** [comment]
Interesting.  The undefined references you're seeing are related to the ESP32 proprietary libraries, which are delivered as binaries in ESP-IDF.  Perhaps your IDF_PATH is not set appropriately?  Or maybe the components/esp32/lib submodule within ESP-IDF has not been updated using "git submodule update"?

To confirm, I am able to successfully build openweave-esp32-demo master using the latest version of ESP-IDF v3.0 on my Ubuntu 18 machine.

Here are the steps I performed to get latest version of ESP-IDF v3.0:

```
git clone https://github.com/espressif/esp-idf.git
cd esp-idf
git checkout release/v3.0
git submodule init
git submodule update
python -m pip install --user -r docs/requirements.txt
```
After this I was able to build openweave-esp32-demo as follows:
```
export ${PATH}:PATH=/home/jay/tools/xtensa-esp32-elf/bin
export IDF_PATH=/home/jay/projects/esp32/esp-idf
git clone https://github.com/openweave/openweave-esp32-demo.git
cd openweave-esp32-demo
git submodule init
git submodule update
make defconfig
make
```

**Comment by Kottapalli-Naveen** [comment]
I re-iterated the steps and it worked.  Thank you.
