### ISSUE TITLE
Error while flashing:  Image length doesn't fit in partition length

### ISSUE THREAD

**Issue by pierredelisle7** [openweave/openweave-esp32-demo#5]
Following the instructions , I successfully built the demo application.
However, when flashing, I get errors (see below).
I have the ESP32-DevKitC, which is one that is referred to in the README.

...
make[5]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/home/pierred/esp-idf/openweave-esp32-demo/build/openweave/share/doc/weave'
 /usr/bin/install --compare -v -m 644 /home/pierred/esp-idf/openweave-esp32-demo/third_party/openweave/CHANGELOG /home/pierred/esp-idf/openweave-esp32-demo/third_party/openweave/LICENSE '/home/pierred/esp-idf/openweave-esp32-demo/build/openweave/share/doc/weave'
LD build/openweave-esp32-demo.elf
esptool.py v2.6
Flashing binaries to serial port /dev/ttyUSB0 (app at offset 0x10000)...
esptool.py v2.6
Serial port /dev/ttyUSB0
Connecting........_____....._
Chip is ESP32D0WDQ5 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 30:ae:a4:d4:64:28
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0220
Compressed 19584 bytes to 11583...
Wrote 19584 bytes (11583 compressed) at 0x00001000 in 1.0 seconds (effective 153.2 kbit/s)...
Hash of data verified.
Compressed 1220688 bytes to 671566...
Wrote 1220688 bytes (671566 compressed) at 0x00010000 in 59.5 seconds (effective 164.2 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 82...
Wrote 3072 bytes (82 compressed) at 0x00008000 in 0.0 seconds (effective 1988.5 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
MONITOR
--- idf_monitor on /dev/ttyUSB0 115200 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:5636
load:0x40078000,len:13860
entry 0x40078fd0
I (26) boot: ESP-IDF v3.0.7-31-g1b1053c86 2nd stage bootloader
I (26) boot: compile time 11:20:14
I (26) boot: Enabling RNG early entropy source...
I (32) boot: SPI Speed      : 40MHz
I (36) boot: SPI Mode       : DIO
I (40) boot: SPI Flash Size : 4MB
I (44) boot: Partition Table:
I (48) boot: ## Label            Usage          Type ST Offset   Length
I (55) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (63) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (70) boot:  2 factory          factory app      00 00 00010000 00100000
I (78) boot: End of partition table
I (82) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x31ca0 (203936) map
I (162) esp_image: segment 1: paddr=0x00041cc8 vaddr=0x3ffc0000 size=0x03eec ( 16108) load
I (169) esp_image: segment 2: paddr=0x00045bbc vaddr=0x40080000 size=0x00400 (  1024) load
0x40080000: _WindowOverflow4 at /home/pierred/esp-idf/components/freertos/./xtensa_vectors.S:1685

I (169) esp_image: segment 3: paddr=0x00045fc4 vaddr=0x40080400 size=0x0a04c ( 41036) load
I (195) esp_image: segment 4: paddr=0x00050018 vaddr=0x400d0018 size=0xe59b8 (940472) map
0x400d0018: _flash_cache_start at ??:?

I (524) esp_image: segment 5: paddr=0x001359d8 vaddr=0x4008a44c size=0x04650 ( 18000) load
0x4008a44c: pvTaskGetThreadLocalStoragePointer at /home/pierred/esp-idf/components/freertos/./tasks.c:4571

E (532) esp_image: Image length 1220688 doesn't fit in partition length 1048576
E (532) boot: Factory app partition is not bootable
E (536) boot: No bootable app partitions in the partition table
user code done

**Comment by jaylogue** [comment]
@pierredelisle7 : A fix for this is out for review.
